### ISSUE TITLE
Error in TemplateSpatialModel serialisation

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#3503]
**Gammapy version**
dev

**Bug description**
A `TemplateSpatialModel` cannot be read back after writing unless `filename` is explicitly specified. The importance of the `filename` is not specified anywhere, and it is rather annoying to find this error at an advanced stage of analysis.
I do not know if we should 
- solve this through documentation
- raise a `warning` if `filename` is not passed upon init
- make it compulsory to write the map as well

Moreover,  I do not want to use the whole map as the template, but a cutout of the same, which works fine on `__init__` but is not reflected in serialisation. 

opinions @registerrier @adonath @QRemy @bkhelifi ?

**To Reproduce**
see: https://github.com/AtreyeeS/test_notebooks/blob/f2c658786f0e307a07c61ca4612e689630da935e/models.ipynb

- content of `test.yaml`
```
-   name: diffuse
    type: SkyModel
    spectral:
        type: PowerLawSpectralModel
        parameters:
        -   name: index
            value: 2.7
            interp: lin
        -   name: amplitude
            value: 2.0e-13
            unit: cm-2 s-1 TeV-1
            interp: log
            scale_method: scale10
        -   name: reference
            value: 1.0
            unit: TeV
            frozen: true
            interp: lin
    spatial:
        type: TemplateSpatialModel
        frame: galactic
        parameters: []
        filename: null
        normalize: true
        unit: 1 / sr
covariance: test_covariance.dat
```
