### ISSUE TITLE
Show linked parameters when printing model

### ISSUE THREAD

**Issue by adonath** [gammapy/gammapy#3692]
Right now linked parameters are not shown in the printout of the model:
```python3
from gammapy.modeling.models import (
    SkyModel,
    FoVBackgroundModel,
    Models,
    PointSpatialModel,
    PowerLawSpectralModel
)

# define model
point = PointSpatialModel(lon_0="0 deg", lat_0="0 deg", frame="galactic")
pwl = PowerLawSpectralModel()

crab = SkyModel(pwl, point, name="crab")

bkg_d1 = FoVBackgroundModel(dataset_name="fermi-dataset")
bkg_d2 = FoVBackgroundModel(dataset_name="cta-dataset")

# link background norm parameters
bkg_d1.spectral_model.norm = bkg_d2.spectral_model.norm

models = Models([crab, bkg_d1, bkg_d2])
print(models)
```
Gives:
```
Models

Component 0: SkyModel

  Name                      : crab
  Datasets names            : None
  Spectral model type       : PowerLawSpectralModel
  Spatial  model type       : PointSpatialModel
  Temporal model type       : 
  Parameters:
    index                   :      2.000   +/-    0.00             
    amplitude               :   1.00e-12   +/- 0.0e+00 1 / (cm2 s TeV)
    reference    (frozen)   :      1.000       TeV         
    lon_0                   :      0.000   +/-    0.00 deg         
    lat_0                   :      0.000   +/-    0.00 deg         

Component 1: FoVBackgroundModel

  Name                      : fermi-dataset-bkg
  Datasets names            : ['fermi-dataset']
  Spectral model type       : PowerLawNormSpectralModel
  Parameters:
    norm                    :      1.000   +/-    0.00             
    tilt         (frozen)   :      0.000                   
    reference    (frozen)   :      1.000       TeV         

Component 2: FoVBackgroundModel

  Name                      : cta-dataset-bkg
  Datasets names            : ['cta-dataset']
  Spectral model type       : PowerLawNormSpectralModel
  Parameters:
    norm                    :      1.000   +/-    0.00             
    tilt         (frozen)   :      0.000                   
    reference    (frozen)   :      1.000       TeV         

```
While this is a simple feature, I think technically it is not as simple to achieve, because there is no "primary" owner of a model parameter and on the parameter level we don't have access to the parent model. A similar thing applies to sharing e.g. spatial and spectral models of sources. Let's collect a few approaches how to possibly make this work in this issue.

**Comment by adonath** [comment]
I think technically we can only achieve something like this, by introducing a `.link()` API and keeping references to the linked parameters internally or similar.

**Comment by adonath** [comment]
Just for completeness, the link is shown when calling `print(models.to_yaml())`:
```
components:
-   name: crab
    type: SkyModel
    spectral:
        type: PowerLawSpectralModel
        parameters:
        -   name: index
            value: 2.0
        -   name: amplitude
            value: 1.0e-12
            unit: cm-2 s-1 TeV-1
        -   name: reference
            value: 1.0
            unit: TeV
            frozen: true
    spatial:
        type: PointSpatialModel
        frame: galactic
        parameters:
        -   name: lon_0
            value: 0.0
            unit: deg
        -   name: lat_0
            value: 0.0
            unit: deg
-   type: FoVBackgroundModel
    datasets_names:
    - fermi-dataset
    spectral:
        type: PowerLawNormSpectralModel
        parameters:
        -   name: norm
            value: 1.0
            link: norm@8POOd7Es
        -   name: tilt
            value: 0.0
            frozen: true
        -   name: reference
            value: 1.0
            unit: TeV
            frozen: true
-   type: FoVBackgroundModel
    datasets_names:
    - cta-dataset
    spectral:
        type: PowerLawNormSpectralModel
        parameters:
        -   name: norm
            value: 1.0
            link: norm@8POOd7Es
        -   name: tilt
            value: 0.0
            frozen: true
        -   name: reference
            value: 1.0
            unit: TeV
            frozen: true
```
