### ISSUE TITLE
Enhance CI

### ISSUE THREAD

**Issue by MRegeard** [gammapy/gammapy#5587]
This PR summaries idea to enhance our CI:

- [x] Pre-commit CI. Ruff pre-commit hook is currently running in as the first step in the CI
- [x] Use [OpenAstronomy github action workflow](https://github.com/OpenAstronomy/github-actions-workflows) Done in #5708 
- [x] Preview docs in PR (see Sunpy PR), (I don't know yet how it is done)
- [x] Use labels to skip jobs. Done in #5938 
- [x] Cron test docstring example and rst file testcode (#5480). Done in #5773

**Comment by registerrier** [comment]
Note regarding preview docs: it is possible to upload the result of a github action with something like:
```
    - name: Upload HTML output
      uses: actions/upload-artifact@v3
      with:
        name: preview-doc-html
        path: _build/html/
```
this will export the html directory in the form of a zip file accessible from the job page.
